// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Udpmsg struct {
	Sn                   uint64   `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Msgtyp               int32    `protobuf:"varint,2,opt,name=msgtyp,proto3" json:"msgtyp,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Udpmsg) Reset()         { *m = Udpmsg{} }
func (m *Udpmsg) String() string { return proto.CompactTextString(m) }
func (*Udpmsg) ProtoMessage()    {}
func (*Udpmsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{0}
}

func (m *Udpmsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Udpmsg.Unmarshal(m, b)
}
func (m *Udpmsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Udpmsg.Marshal(b, m, deterministic)
}
func (m *Udpmsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Udpmsg.Merge(m, src)
}
func (m *Udpmsg) XXX_Size() int {
	return xxx_messageInfo_Udpmsg.Size(m)
}
func (m *Udpmsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Udpmsg.DiscardUnknown(m)
}

var xxx_messageInfo_Udpmsg proto.InternalMessageInfo

func (m *Udpmsg) GetSn() uint64 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *Udpmsg) GetMsgtyp() int32 {
	if m != nil {
		return m.Msgtyp
	}
	return 0
}

func (m *Udpmsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Udpmsg)(nil), "message.udpmsg")
}

func init() { proto.RegisterFile("message/message.proto", fileDescriptor_ebceca9e8703e37f) }

var fileDescriptor_ebceca9e8703e37f = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x92, 0x0b, 0x17, 0x5b, 0x69, 0x4a, 0x41, 0x6e, 0x71, 0xba, 0x10, 0x1f, 0x17, 0x53, 0x71, 0x9e,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x53, 0x71, 0x9e, 0x90, 0x18, 0x17, 0x5b, 0x6e, 0x71,
	0x7a, 0x49, 0x65, 0x81, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x94, 0x27, 0x24, 0xc4, 0xc5,
	0x92, 0x92, 0x58, 0x92, 0x28, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x27, 0xb1, 0x81,
	0x4d, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x29, 0xc1, 0x74, 0x35, 0x6e, 0x00, 0x00, 0x00,
}
