// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msghead.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgHead struct {
	MsgId                int32    `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	LocalStationId       []byte   `protobuf:"bytes,2,opt,name=localStationId,proto3" json:"localStationId,omitempty"`
	RemoteStationId      []byte   `protobuf:"bytes,3,opt,name=remoteStationId,proto3" json:"remoteStationId,omitempty"`
	Headinfo             []byte   `protobuf:"bytes,16,opt,name=headinfo,proto3" json:"headinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgHead) Reset()         { *m = MsgHead{} }
func (m *MsgHead) String() string { return proto.CompactTextString(m) }
func (*MsgHead) ProtoMessage()    {}
func (*MsgHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd4d2066a25f531b, []int{0}
}

func (m *MsgHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgHead.Unmarshal(m, b)
}
func (m *MsgHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgHead.Marshal(b, m, deterministic)
}
func (m *MsgHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHead.Merge(m, src)
}
func (m *MsgHead) XXX_Size() int {
	return xxx_messageInfo_MsgHead.Size(m)
}
func (m *MsgHead) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHead.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHead proto.InternalMessageInfo

func (m *MsgHead) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *MsgHead) GetLocalStationId() []byte {
	if m != nil {
		return m.LocalStationId
	}
	return nil
}

func (m *MsgHead) GetRemoteStationId() []byte {
	if m != nil {
		return m.RemoteStationId
	}
	return nil
}

func (m *MsgHead) GetHeadinfo() []byte {
	if m != nil {
		return m.Headinfo
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgHead)(nil), "message.MsgHead")
}

func init() { proto.RegisterFile("msghead.proto", fileDescriptor_cd4d2066a25f531b) }

var fileDescriptor_cd4d2066a25f531b = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2d, 0x4e, 0xcf,
	0x48, 0x4d, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x4f, 0x55, 0xea, 0x65, 0xe4, 0x62, 0xf7, 0x2d, 0x4e, 0xf7, 0x48, 0x4d, 0x4c, 0x11, 0x12,
	0xe1, 0x62, 0xcd, 0x2d, 0x4e, 0xf7, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70,
	0x84, 0xd4, 0xb8, 0xf8, 0x72, 0xf2, 0x93, 0x13, 0x73, 0x82, 0x4b, 0x12, 0x4b, 0x32, 0xf3, 0xf3,
	0x3c, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0xd0, 0x44, 0x85, 0x34, 0xb8, 0xf8, 0x8b,
	0x52, 0x73, 0xf3, 0x4b, 0x52, 0x11, 0x0a, 0x99, 0xc1, 0x0a, 0xd1, 0x85, 0x85, 0xa4, 0xb8, 0x38,
	0x40, 0x4e, 0xc9, 0xcc, 0x4b, 0xcb, 0x97, 0x10, 0x00, 0x2b, 0x81, 0xf3, 0x93, 0xd8, 0xc0, 0xee,
	0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xf0, 0x8e, 0x0d, 0xb0, 0x00, 0x00, 0x00,
}
