// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package file

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Udpfile struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Strhash              []byte   `protobuf:"bytes,2,opt,name=strhash,proto3" json:"strhash,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Streamid             uint64   `protobuf:"varint,4,opt,name=streamid,proto3" json:"streamid,omitempty"`
	Resume               bool     `protobuf:"varint,5,opt,name=resume,proto3" json:"resume,omitempty"`
	StartSize            int64    `protobuf:"varint,6,opt,name=startSize,proto3" json:"startSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Udpfile) Reset()         { *m = Udpfile{} }
func (m *Udpfile) String() string { return proto.CompactTextString(m) }
func (*Udpfile) ProtoMessage()    {}
func (*Udpfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *Udpfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Udpfile.Unmarshal(m, b)
}
func (m *Udpfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Udpfile.Marshal(b, m, deterministic)
}
func (m *Udpfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Udpfile.Merge(m, src)
}
func (m *Udpfile) XXX_Size() int {
	return xxx_messageInfo_Udpfile.Size(m)
}
func (m *Udpfile) XXX_DiscardUnknown() {
	xxx_messageInfo_Udpfile.DiscardUnknown(m)
}

var xxx_messageInfo_Udpfile proto.InternalMessageInfo

func (m *Udpfile) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Udpfile) GetStrhash() []byte {
	if m != nil {
		return m.Strhash
	}
	return nil
}

func (m *Udpfile) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Udpfile) GetStreamid() uint64 {
	if m != nil {
		return m.Streamid
	}
	return 0
}

func (m *Udpfile) GetResume() bool {
	if m != nil {
		return m.Resume
	}
	return false
}

func (m *Udpfile) GetStartSize() int64 {
	if m != nil {
		return m.StartSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Udpfile)(nil), "file.udpfile")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x4d, 0x0a, 0xc2, 0x30,
	0x10, 0x46, 0x19, 0x1b, 0xdb, 0x3a, 0xb8, 0x9a, 0x85, 0x0c, 0xe2, 0x22, 0xb8, 0xca, 0xca, 0x8d,
	0x37, 0x89, 0x27, 0x88, 0x74, 0xa4, 0x05, 0x6b, 0x4b, 0x26, 0xdd, 0x78, 0x17, 0xef, 0x2a, 0x09,
	0xfe, 0xec, 0xde, 0x7b, 0x0c, 0xc3, 0x87, 0x78, 0x1b, 0xee, 0x72, 0x9a, 0xe3, 0x94, 0x26, 0x32,
	0x99, 0x8f, 0x2f, 0xc0, 0x66, 0xe9, 0xe6, 0xcc, 0x44, 0x68, 0x1e, 0x61, 0x14, 0x06, 0x0b, 0x6e,
	0xeb, 0x0b, 0x13, 0x63, 0xa3, 0x29, 0xf6, 0x41, 0x7b, 0x5e, 0x95, 0xfc, 0xd5, 0x7c, 0xad, 0xc3,
	0x53, 0xb8, 0xb2, 0xe0, 0x8c, 0x2f, 0x4c, 0x7b, 0x6c, 0x35, 0x45, 0x09, 0xe3, 0xd0, 0xb1, 0x29,
	0xfd, 0xe7, 0xb4, 0xc3, 0x3a, 0x8a, 0x2e, 0xa3, 0xf0, 0xda, 0x82, 0x6b, 0xfd, 0xc7, 0xe8, 0x80,
	0x1b, 0x4d, 0x21, 0xa6, 0x4b, 0x7e, 0x56, 0x5b, 0x70, 0x95, 0xff, 0x87, 0x6b, 0x5d, 0xc6, 0x9e,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x08, 0xa6, 0x3f, 0xba, 0x00, 0x00, 0x00,
}
