// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package udpmessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Udpmsg struct {
	Sn                   uint64   `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Pos                  uint64   `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Msgtyp               int32    `protobuf:"varint,3,opt,name=msgtyp,proto3" json:"msgtyp,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Udpmsg) Reset()         { *m = Udpmsg{} }
func (m *Udpmsg) String() string { return proto.CompactTextString(m) }
func (*Udpmsg) ProtoMessage()    {}
func (*Udpmsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Udpmsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Udpmsg.Unmarshal(m, b)
}
func (m *Udpmsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Udpmsg.Marshal(b, m, deterministic)
}
func (m *Udpmsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Udpmsg.Merge(m, src)
}
func (m *Udpmsg) XXX_Size() int {
	return xxx_messageInfo_Udpmsg.Size(m)
}
func (m *Udpmsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Udpmsg.DiscardUnknown(m)
}

var xxx_messageInfo_Udpmsg proto.InternalMessageInfo

func (m *Udpmsg) GetSn() uint64 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *Udpmsg) GetPos() uint64 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *Udpmsg) GetMsgtyp() int32 {
	if m != nil {
		return m.Msgtyp
	}
	return 0
}

func (m *Udpmsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Udpmsgack struct {
	Sn                   uint64   `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Pos                  uint64   `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Arrpos               []uint64 `protobuf:"varint,3,rep,packed,name=arrpos,proto3" json:"arrpos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Udpmsgack) Reset()         { *m = Udpmsgack{} }
func (m *Udpmsgack) String() string { return proto.CompactTextString(m) }
func (*Udpmsgack) ProtoMessage()    {}
func (*Udpmsgack) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Udpmsgack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Udpmsgack.Unmarshal(m, b)
}
func (m *Udpmsgack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Udpmsgack.Marshal(b, m, deterministic)
}
func (m *Udpmsgack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Udpmsgack.Merge(m, src)
}
func (m *Udpmsgack) XXX_Size() int {
	return xxx_messageInfo_Udpmsgack.Size(m)
}
func (m *Udpmsgack) XXX_DiscardUnknown() {
	xxx_messageInfo_Udpmsgack.DiscardUnknown(m)
}

var xxx_messageInfo_Udpmsgack proto.InternalMessageInfo

func (m *Udpmsgack) GetSn() uint64 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *Udpmsgack) GetPos() uint64 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *Udpmsgack) GetArrpos() []uint64 {
	if m != nil {
		return m.Arrpos
	}
	return nil
}

func init() {
	proto.RegisterType((*Udpmsg)(nil), "udpmessage.udpmsg")
	proto.RegisterType((*Udpmsgack)(nil), "udpmessage.udpmsgack")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2a, 0x4d, 0x29, 0x80, 0x8a,
	0x28, 0x85, 0x71, 0xb1, 0x81, 0x78, 0xc5, 0xe9, 0x42, 0x7c, 0x5c, 0x4c, 0xc5, 0x79, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x4c, 0xc5, 0x79, 0x42, 0x02, 0x5c, 0xcc, 0x05, 0xf9, 0xc5, 0x12,
	0x4c, 0x60, 0x01, 0x10, 0x53, 0x48, 0x8c, 0x8b, 0x2d, 0xb7, 0x38, 0xbd, 0xa4, 0xb2, 0x40, 0x82,
	0x59, 0x81, 0x51, 0x83, 0x35, 0x08, 0xca, 0x13, 0x12, 0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94,
	0x60, 0x51, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x95, 0x5c, 0xb9, 0x38, 0x21, 0xe6, 0x26, 0x26,
	0x67, 0x13, 0x67, 0x74, 0x62, 0x51, 0x11, 0x48, 0x90, 0x59, 0x81, 0x59, 0x83, 0x25, 0x08, 0xca,
	0x4b, 0x62, 0x03, 0xbb, 0xd8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x38, 0xde, 0x05, 0xa7, 0xc2,
	0x00, 0x00, 0x00,
}
