// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet.proto

package packet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UDPPacketData struct {
	SerialNo             uint64   `protobuf:"varint,1,opt,name=serialNo,proto3" json:"serialNo,omitempty"`
	TotalCnt             uint32   `protobuf:"varint,16,opt,name=totalCnt,proto3" json:"totalCnt,omitempty"`
	PosNum               uint32   `protobuf:"varint,2,opt,name=posNum,proto3" json:"posNum,omitempty"`
	DataType             uint32   `protobuf:"varint,3,opt,name=dataType,proto3" json:"dataType,omitempty"`
	TryCnt               uint32   `protobuf:"varint,17,opt,name=tryCnt,proto3" json:"tryCnt,omitempty"`
	Len                  int32    `protobuf:"varint,4,opt,name=len,proto3" json:"len,omitempty"`
	TransInfo            []byte   `protobuf:"bytes,18,opt,name=transInfo,proto3" json:"transInfo,omitempty"`
	Finished             bool     `protobuf:"varint,19,opt,name=finished,proto3" json:"finished,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UDPPacketData) Reset()         { *m = UDPPacketData{} }
func (m *UDPPacketData) String() string { return proto.CompactTextString(m) }
func (*UDPPacketData) ProtoMessage()    {}
func (*UDPPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}

func (m *UDPPacketData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UDPPacketData.Unmarshal(m, b)
}
func (m *UDPPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UDPPacketData.Marshal(b, m, deterministic)
}
func (m *UDPPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UDPPacketData.Merge(m, src)
}
func (m *UDPPacketData) XXX_Size() int {
	return xxx_messageInfo_UDPPacketData.Size(m)
}
func (m *UDPPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_UDPPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_UDPPacketData proto.InternalMessageInfo

func (m *UDPPacketData) GetSerialNo() uint64 {
	if m != nil {
		return m.SerialNo
	}
	return 0
}

func (m *UDPPacketData) GetTotalCnt() uint32 {
	if m != nil {
		return m.TotalCnt
	}
	return 0
}

func (m *UDPPacketData) GetPosNum() uint32 {
	if m != nil {
		return m.PosNum
	}
	return 0
}

func (m *UDPPacketData) GetDataType() uint32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

func (m *UDPPacketData) GetTryCnt() uint32 {
	if m != nil {
		return m.TryCnt
	}
	return 0
}

func (m *UDPPacketData) GetLen() int32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *UDPPacketData) GetTransInfo() []byte {
	if m != nil {
		return m.TransInfo
	}
	return nil
}

func (m *UDPPacketData) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

func (m *UDPPacketData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UDPPacketData)(nil), "packet.UDPPacketData")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor_e9ef1a6541f9f9e7) }

var fileDescriptor_e9ef1a6541f9f9e7 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x89, 0xdb, 0x2d, 0x6b, 0xd8, 0x85, 0x75, 0x04, 0x19, 0xc4, 0x43, 0xf0, 0x94, 0x93,
	0x17, 0x1f, 0xc1, 0xbd, 0x78, 0x29, 0x25, 0xe8, 0x03, 0x8c, 0x36, 0xc5, 0x62, 0x4d, 0x42, 0x32,
	0x1e, 0xfa, 0xdc, 0xbe, 0x80, 0x24, 0xd1, 0xee, 0xed, 0xff, 0xf2, 0xf3, 0xe5, 0x87, 0x91, 0xfb,
	0x40, 0xef, 0x9f, 0x96, 0x1f, 0x42, 0xf4, 0xec, 0xa1, 0xad, 0x74, 0xff, 0x23, 0xe4, 0xe1, 0xf5,
	0xd4, 0xf7, 0x85, 0x4e, 0xc4, 0x04, 0xb7, 0x72, 0x97, 0x6c, 0x9c, 0x68, 0xee, 0x3c, 0x0a, 0x25,
	0x74, 0x63, 0x56, 0xce, 0x1d, 0x7b, 0xa6, 0xf9, 0xc9, 0x31, 0x1e, 0x95, 0xd0, 0x07, 0xb3, 0x32,
	0xdc, 0xc8, 0x36, 0xf8, 0xd4, 0x7d, 0x7f, 0xe1, 0x45, 0x69, 0xfe, 0x28, 0x3b, 0x03, 0x31, 0xbd,
	0x2c, 0xc1, 0xe2, 0xa6, 0x3a, 0xff, 0x9c, 0x1d, 0x8e, 0x4b, 0xfe, 0xed, 0xaa, 0x3a, 0x95, 0xe0,
	0x28, 0x37, 0xb3, 0x75, 0xd8, 0x28, 0xa1, 0xb7, 0x26, 0x47, 0xb8, 0x93, 0x97, 0x1c, 0xc9, 0xa5,
	0x67, 0x37, 0x7a, 0x04, 0x25, 0xf4, 0xde, 0x9c, 0x1f, 0xf2, 0xc6, 0x38, 0xb9, 0x29, 0x7d, 0xd8,
	0x01, 0xaf, 0x95, 0xd0, 0x3b, 0xb3, 0x32, 0x80, 0x6c, 0xf2, 0x1e, 0x6e, 0x8b, 0x54, 0xf2, 0x5b,
	0x5b, 0x8e, 0xf0, 0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x54, 0x2c, 0x7b, 0x14, 0x01, 0x00,
	0x00,
}
